config/routes.rb
FnafApp::Application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :fnafs

  root 'static#home'
  get '/about' => 'static#about'

  get '/sign-in' => 'sessions#new', as: "sign_in"
  post '/sign-in' => 'sessions#create'
  delete '/sign-out' => 'sessions#destroy', as: "sign_out"

    get '/signup' => 'users#new'
    post '/users' => 'users#create'

  

end

app/models/fnaf.rb
class Fnaf < ActiveRecord::Base
  validates_presence_of :name, :species, :gender
  validates_format_of :picture, :with => %r{\.(png|jpg|jpeg|gif)$}i, :message => "Please submit the URL of an image ending in .jpg, .jpeg, .png, or .gif OR leave this field blank", :multiline => true, allow_blank: true

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  validates_uniqueness_of :email, :message => "Sorry, this email is already registered. Please use another."
  has_secure_password

end

app/controllers/fnafs_controller.rb
class FnafsController < ApplicationController
  before_action :set_fnaf, only: [:show, :edit, :update, :destroy]
  before_action :only_allow_signed_in_users, except: [:index, :show]

  # GET /fnafs
  # GET /fnafs.json
  def index
    respond_to do |format|
      format.html do
        @fnafs = Fnaf.search(params[:search]).paginate(page: params[:page], per_page: 5)
      end
      format.json do
        @fnafs = Fnaf.all
      end
    end
  end

  # GET /fnafs/1
  # GET /fnafs/1.json
  def show
    # @fnaf = Fnaf.find(params[:id])
  end

  # GET /fnafs/new
  def new
    @fnaf = Fnaf.new
  end

  # GET /fnafs/1/edit
  def edit
  end

  # POST /fnafs
  # POST /fnafs.json
  def create
    @fnaf = Fnaf.new(fnaf_params)

    respond_to do |format|
      if @fnaf.save
        format.html { redirect_to @fnaf, notice: 'Fnaf was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fnaf }
      else
        format.html { render action: 'new' }
        format.json { render json: @fnaf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fnafs/1
  # PATCH/PUT /fnafs/1.json
  def update
    respond_to do |format|
      if @fnaf.update(fnaf_params)
        format.html { redirect_to @fnaf, notice: 'Fnaf was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fnaf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fnafs/1
  # DELETE /fnafs/1.json
  def destroy
    @fnaf.destroy
    respond_to do |format|
      format.html { redirect_to fnafs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fnaf
      @fnaf = Fnaf.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fnaf_params
      params.require(:fnaf).permit(:name, :picture, :species, :gender, :first_game, :second_game, :third_game, :search)
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      # Store the user's id in the session, to keep track of who's signed in
      session[:user_id] = user.id
      # Redirect to the `root_url` and show a notice that the user has successfully signed in
      redirect_to root_url, notice: 'Successfully signed in!'
    # If the credentials the user gave were bad
    else
      flash.alert = 'Invalid email/password combination. Please try again.'
      # On the view for the `new` action
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Successfully signed out!'
  end
end

app/controllers/users_controller.rb
# app/controllers/users_controller.rb

class UsersController < ApplicationController

  def new
    end

    def create
      user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      flash.alert = 'Welcome! Thanks for signing up.'
      redirect_to '/'
    else
        flash.alert = 'Could not create new account. Possible errors: passwords did not match or email is taken.'
        redirect_to '/sign-in'
    end

  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/views/fnafs/_form.html.erb
<%= form_for(@fnaf) do |f| %>
  <% if @fnaf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fnaf.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @fnaf.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :species %><br>
    <%= f.text_area :species %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_area :gender %>
  </div>
  <div class="field">
    <%= f.label :first_game %><br>
    <%= f.check_box :first_game %>
  </div>
  <div class="field">
    <%= f.label :second_game %><br>
    <%= f.check_box :second_game %>
  </div>
  <div class="field">
    <%= f.label :third_game %><br>
    <%= f.check_box :third_game %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fnafs/index.html.erb
<center>

  <p>
    <%= link_to 'Home', root_path %> |
    <%= link_to 'About', about_path %> |
    <%= link_to 'Character Directory', fnafs_path %>
  </p>

  <hr>

  <h1>Meet the Characters</h1>

  <p> If you'd like, you can even add your own OC by clicking 'New Character' at the bottom of this page and filling in the information. It won't actually put him in the game, but you can pretend he's in there by placing him in the database.</p>

  <hr>

  <%= will_paginate @fnafs %>
  <table style="width:800px">
    <thead>
      <tr>
        <th>Name</th>
        <th>Picture</th>
        <th>Species</th>
        <th>Gender</th>
        <th>First Game</th>
        <th>Second Game</th>
        <th>Third Game</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @fnafs.each do |fnaf| %>
      <tr>
        <td><%= fnaf.name %></td>
        <td><%= image_tag fnaf.picture %></td>
        <td><%= fnaf.species %></td>
        <td><%= fnaf.gender %></td>
        <td><%= fnaf.first_game %></td>
        <td><%= fnaf.second_game %></td>
        <td><%= fnaf.third_game %></td>
        <td><%= link_to 'Show', fnaf %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_fnaf_path(fnaf) %></td>
        <td><%= link_to 'Destroy', fnaf, method: :delete, data: { confirm: 'Are you sure you want to destroy this monstrosity once and for all?' } %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate @fnafs %>

  Search for a character by name:

    <%= form_tag fnafs_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>

  <hr>

  <%= link_to 'Add Character', new_fnaf_path %>
</center>

app/views/users/new.html.erb
<!-- app/views/users/new.html.erb -->

<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>

  <%= f.submit "Submit" %>

<% end %>